corner_detector:
    laser_topic: "/amigo/base_laser/scan"
    corner_threshold: 0.07
    step_size: 70
    frame_id: "/amigo/base_laser"
    jump_size: 0.05
    visualization:
        points:
            name: "corners"
            color: {r: 0, g: 1, b: 0}
        lines:
            name: "corner_lines"
            color: {r: 0, g: 0, b: 1}
odom_tracker:
    map_frame: "map"
    odom_frame: "amigo/odom"
    base_link_frame: "amigo/base_laser"
graph_filename: "robotics_testlab_B.yaml"
visualization:
    points:
        name: "graph_nodes"
        color: {r: 1, g: 0, b: 0}
