corner_detector:
    laser_topic: "/amigo/base_laser/scan"
    corner_threshold: 0.07
    step_size: 70
    frame_id: "/amigo/base_laser"
    jump_size: 0.05
    visualization:
        points_name: "corners"
        lines_name: "line_segments"
