corner_detector:
    laser_topic: "/amigo/base_laser/scan"
    sensor_noise_std_dev: 0.05
    corner_threshold: 0.08
    step_size: 0.2
    frame_id: "/amigo/base_laser"
    jump_size: 0.10
    visualization:
        lifetime: 0.1
        points:
            name: "corners"
            color: {r: 0, g: 1, b: 0}
        lines:
            name: "corner_lines"
            color: {r: 0, g: 1, b: 1}
association:
    max_association_distance: 0.10
    max_no_std_devs: 0.1
odom_tracker:
    map_frame: "map"
    odom_frame: "amigo/odom"
    base_link_frame: "amigo/base_laser"
graph_filename: "robotics_testlab_B_partly.yaml"
initial_pose:
    - position: {x: 2.11, y: -0.76}
      node: 2
    - position: {x: 0.12, y: 0.50}
      node: 5
visualization:
    lifetime: 0.1
    points:
        name: "graph_nodes"
        color: {r: 1, g: 0, b: 0}
    lines:
        name: "graph_edges"
        color: {r: 1, g: 1, b: 0}
