corner_detector:
    laser_topic: "/amigo/base_laser/scan"
    sensor_noise_std_dev: 0.05
    corner_threshold: 0.08
    step_size: 0.2
    frame_id: "/amigo/base_laser"
    jump_size: 0.10
    visualization:
        lifetime: 0
        points:
            name: "corners"
            color: {r: 0, g: 1, b: 0}
        lines:
            name: "corner_lines"
            color: {r: 0, g: 1, b: 1}
    jumps_as_corners: 1
association:
    association_modules:
      - type: "nearest_neighbor"
        min_association_prob: 0.95
      - type: "edge_tension"
        min_association_prob: 0.9
odom_tracker:
    odom_frame: "amigo/odom"
    sensor_frame: "amigo/base_laser"
graph_filename: "rokus_experiment3.yaml"
initial_pose:
    - position: {x: 1.94, y: -0.6}
      node: 2
      std_dev: 0.10
    - position: {x: 1.96, y: 0.6}
      node: 3
      std_dev: 0.10
target_node: 21
visualization:
    lifetime: 0
    points:
        name: "graph_nodes"
        color: {r: 1, g: 0, b: 0}
    lines:
        name: "graph_edges"
        color: {r: 1, g: 1, b: 0}
